### ISSUE TITLE
您好 关于数据集的一些问题 

### ISSUE THREAD

**Issue by SuZhenQ** [AndersonStra/MuKEA#11]
大神您好 
为什么filter_data对vqa做前两类过滤 把地点都过滤了，

**Comment by AndersonStra** [comment]
事实上并没有过滤，这里代码我忘记修改了

**Comment by SZQ1995** [comment]
好的 感谢您的及时回复 。
可以冒昧问下vqa2.0、 krvqa 和okvqa之间的文件的共同点和不同点是啥吗 ？看了代码中 文件相关的引入 感觉有点乱（不知道具体差异）
还有okvqa目录下prepare_annotation.py中的文件似乎在仓库中和谷歌盘上并未发现

**Comment by AndersonStra** [comment]
不太理解你的意思，不同点就是数据集本身的差异，具体差异可以读取每个文件查看内容。```prepare_annotation.py``` 这个文件是为了处理数据集的，但是处理好的数据集已经提供在谷歌盘中了不需要再运行

**Comment by AndersonStra** [comment]
pickle文件是图像的Bottom-up特征，因为太大不方便上传所以我在readme中详细写了生成的步骤。VG数据集部分图像来自COCO

**Comment by SZQ1995** [comment]
好的 多谢大佬 我再瞅瞅

**Comment by SuZhenQ** [comment]
您好  我想问下为什么对vqav2 构建答案词典 为什么代码中取前3500个

**Comment by AndersonStra** [comment]
取前3500个是大部分论文的common setting， 这里只是构建了一个同样的词表方便后续实验与其他模型进行比较，代码针对不同的实验设置会有变动，提供的词表文件是没有取前3500个的

**Comment by SuZhenQ** [comment]
理解了 谢谢大佬

**Comment by SuZhenQ** [comment]
请问下，用vqav2做预训练 那针对okvqa微调阶段 答案词典是单纯的okvqa 还是vqav2+okvqa 我看您代码中微调用的是pretrain_dic_all_filter这个文件 这个all是否代表是后者的组合，这种有什么优势呢

**Comment by AndersonStra** [comment]
并不存在优势的说法，对于通用模型，词表肯定是越大越好

**Comment by SuZhenQ** [comment]
那我想问下 paper中的实验效果 词典是基于单纯的okvqa的train 还是也融合了vqav2

**Comment by YilinGeStudy** [comment]
您好，我在运行“python train.py --embedding --model_dir model_save_dir --dataset finetune-dataset/okvqa/krvqa/vqav2 --pretrain --accumulate --validate”时，系统执行到“for qid,item in train_row.items():”时，会报错“NameError: name 'train_row' is not defined“。请问如何解决呢？是我漏掉了什么步骤吗？

**Comment by YilinGeStudy** [comment]
我刚刚提的出错的语句是在”dataset.py“文件中的第93行，我单独执行dataset.py文件系统会输出9009，但是我执行“python train.py --embedding --model_dir model_save_dir --dataset finetune-dataset/okvqa/krvqa/vqav2 --pretrain --accumulate --validate”时会出现报错“NameError: name 'train_row' is not defined“。麻烦您指点一下解决方案
