### ISSUE TITLE
ok-vqa 的一些疑惑

### ISSUE THREAD

**Issue by ZHUZHU1995** [AndersonStra/MuKEA#12]
大佬，您好
             我想问下 okvqa 数据集实验中训练集 验证集 测试集 是如何是咋划分的 ？ 官网下载只有train 和test，test下载路径的文件又是val 有点蒙了。
感谢您，希望得到您的回复。

**Comment by AndersonStra** [comment]
OKVQA没有验证集，测试集图像使用的是COCO的验证集

**Comment by ZHUZHU1995** [comment]
谢谢 ，请问下您计算概率的方式 答案出现2次以上 即返回1。我看其他关于VQA 2.0 里面 他是3次返回0.9 。采用哪种更合适，如果直接看评价公式 我也感觉是2次以上即可

**Comment by AndersonStra** [comment]
对于OKVQA数据集不存在3次的情况所以是1（出现次数只可能是2的倍数），对于VQA2.0数据集1 2 3次分别对应0.3 0.6 0.9，详细计算过程可以看https://github.com/ntusteeian/VQA_evaluation/blob/master/PythonEvaluationTools/vqaEvaluation/vqaEval.py
