### ISSUE TITLE
关于预训练问题

### ISSUE THREAD

**Issue by cmcv2022** [AndersonStra/MuKEA#13]
请问文中所说的在VQA2.0上进行预训练，不需要执行python train.py --embedding --model_dir model_save_dir --dataset **vqav2** --pretrain --accumulate --validate命令么？其他数据集的预训练呢

**Comment by AndersonStra** [comment]
因为每个数据集的词表暂时没有合并，所以dataset的参数预训练和微调的时候保持一致就可以了，加了--pretrain参数后就会在vqa2.0上预训练，不用更改dataset参数

**Comment by cmcv2022** [comment]
好的，谢谢大佬
