### ISSUE TITLE
关于prepare_annotation.py的问题

### ISSUE THREAD

**Issue by a670642151** [AndersonStra/MuKEA#14]
请问使用prepare_annotation.py处理完v2_OpenEnded_mscoco_test2015_questions.json和v2_mscoco_val2014_annotations.json后，得到的vqa_test.json中的multi_answers和question对应不上是怎么回事？

**Comment by AndersonStra** [comment]
这个代码是用来分别处理train，val，test的。修改了文件名错误的问题，现在是一致的了

**Comment by a670642151** [comment]
> 这个代码是用来分别处理train，val，test的。修改了文件名错误的问题，现在是一致的了
明白了，谢谢大佬

**Comment by a670642151** [comment]
明白了，谢谢大佬
