### ISSUE TITLE
关于vqa_img_feature_test_dev.pickle文件的问题

### ISSUE THREAD

**Issue by yanhan111** [AndersonStra/MuKEA#15]
您好，我在复现您的代码的时候 遇到了一些问题 在运行train.py时 报错没有找到vqa_img_feature_test_dev.pickle，我重新运行了tsv2feature.py文件 和tsv2feature_objects.py文件 也没有生成vqa_img_feature_test_dev.pickle文件 但是data文件夹中是有vqa_img_feature_train_dev.pickle和vqa_img_feature_val_dev.pickle文件的

**Comment by AndersonStra** [comment]
你是需要在vqav2数据集上做测试吗

**Comment by yanhan111** [comment]
是的大佬

**Comment by AndersonStra** [comment]
test特征文件可以从https://github.com/peteanderson80/bottom-up-attention#pretrained-features下载，然后用我提供的tsv2feature处理一下即可，train，val，test都有

**Comment by yanhan111** [comment]
抱歉 再次打扰，我根据您的tsv2feature脚本重新处理后 还是无法 获得 vqa_img_feature_test_dev.pickle文件 ，请问 目录下只是使用了trainval2014_resnet101_faster_rcnn_genome_36.tsv和test2015_resnet101_faster_rcnn_genome_36.tsv文件吗。您的脚本代码tsv2feature中我并未看到test特征文件的相关内容

**Comment by AndersonStra** [comment]
将 split 参数更改为 test即可

**Comment by yanhan111** [comment]
我明白了 谢谢大佬

**Comment by YilinGeStudy** [comment]
如何获取vqa_test_dev_questions.json文件呢？在您分享的目录里没找到，能麻烦再指点一下吗？

**Comment by ProudZhangXiaolong** [comment]
> 抱歉请容许我再次打扰 请问预训练模型的最佳正确率是多少，预训练模型最好的我只能跑到29.46微调后无法达到论文指标。预训练的时候计算损失函数需要加入loss_cl损失吗？因为我发现是否加入会对微调的结果有一定的影响。



> 我明白了 谢谢大佬

不会报错吗？vqa_test.json 与vqa_img_feature_test.pickle 数据不对等啊
