### ISSUE TITLE
损失函数问题

### ISSUE THREAD

**Issue by yuemingPAN** [AndersonStra/MuKEA#16]
您好，我看到代码里写了三个损失函数，但是为什么只用了两个呢，loss_graph代表的是论文中的Triplet TransE Loss，loss_mse代表的是Triplet Consistency Loss对吗，然后loss_cls虽然计算了但没有使用
![1](https://user-images.githubusercontent.com/48699475/198027511-d8b13910-3263-4962-a43e-ddb37a165336.png)

**Comment by AndersonStra** [comment]
谢谢指出，已修改
