### ISSUE TITLE
关于预训练过程的问题

### ISSUE THREAD

**Issue by yjmlaile** [AndersonStra/MuKEA#18]
您好，我在预训练时设置了dataset为krvqa，训练过程中出现了验证集准确率先稳步上升，然后一直稳步下降的情况，请问这种情况是否是正常的？感谢！

**Comment by yjmlaile** [comment]
通过其他issue了解到这个现象是正常的！

**Comment by xzr912** [comment]
> 您好，我在预训练时设置了dataset为krvqa，训练过程中出现了验证集准确率先稳步上升，然后一直稳步下降的情况，请问这种情况是否是正常的？感谢！

![image](https://github.com/AndersonStra/MuKEA/assets/44090979/e96e8fc6-eee9-47f1-8f21-4a9e36d024ef)
![image](https://github.com/AndersonStra/MuKEA/assets/44090979/d65377f3-cb13-437c-867e-5198354d390c)
请问您在微调时又遇到这种错误吗
