### ISSUE TITLE
hallo，How to acquire the file of“cocobu_att”and“cocobu_box” in the prepare_img.py？thank you！

### ISSUE THREAD

**Issue by wangfengjuan** [AndersonStra/MuKEA#2]
hallo，How to acquire the file of“cocobu_att”and“cocobu_box”in the prepare_img.py？thank you！

**Comment by AndersonStra** [comment]
`cocobu_att` and `cocobu_box` are image features and corresponding bounding boxes， please refer to  https://github.com/AndersonStra/MuKEA/issues/1 to obtain the  `image_feature_train.pickle`, I haven't found a proper way to upload image feature files so far, I will provide the new script further.

**Comment by AndersonStra** [comment]
I have updated the script to help generate the pickle file from the original bottom-up attention file.

**Comment by wangfengjuan** [comment]
谢谢，感谢您的成果分享，让我们受益匪浅！
| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/6/2022 ***@***.***> wrote：

I have updated the script to help generate the pickle file from the original bottom-up attention file.

**Comment by wangfengjuan** [comment]
您好，您方便提供train2014_resnet101_faster_rcnn_genome_36.tsv和val2014_resnet101_faster_rcnn_genome_36.tsv这两个文件嘛？万分感谢啊
祝好！
凤娟
| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/6/2022 ***@***.***> wrote：

I have updated the script to help generate the pickle file from the original bottom-up attention file.

**Comment by AndersonStra** [comment]
这两个特征文件请从 bottom-up-attention仓库中下载 [链接](https://github.com/peteanderson80/bottom-up-attention#pretrained-features)  请注意是36-fixed-feature

**Comment by wangfengjuan** [comment]
您好！ bottom-up-attention仓库中的特征文件train和val是一个文件，您方便提供train和val这两个单独的文件嘛？万分感谢啊!
祝好！


| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/7/2022 ***@***.***> wrote：

这两个特征文件请从 bottom-up-attention仓库中下载 链接 请注意是36-fixed-feature

**Comment by AndersonStra** [comment]
方便提供一下你下载得到的特征文件名吗，我未使用该链接的特征，可以提供一下文件名我修改一下代码，因为代码中我默认train和val是分开的

**Comment by AndersonStra** [comment]
不好意思，因为我这边没有这个特征文件所以不方便测试，我刚更新了代码，如果有什么问题还请告诉我。正常的话train是82783张图片，val是40504张图片

**Comment by wangfengjuan** [comment]
好的，看到您的修改了，感谢您的回复，我先复现下看看结果。
祝好！


| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/7/2022 ***@***.***> wrote：

不好意思，因为我这边没有这个特征文件所以不方便测试，我刚更新了代码，如果有什么问题还请告诉我。正常的话train是82783张图片，val是40504张图片

**Comment by wangfengjuan** [comment]
您好，不好意思这么晚打扰您，有个程序运行上的问题可以请教您嘛？在网上试了好几个方案也没有解决。是在V100上运行的时候，总是会出现下面的错误（图片在附件）。cuda版本是10.1,   tersorflow=2.8.0,    cudatoolkit=11.0.221，期待您的回复。谢谢！
祝好！




| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/7/2022 ***@***.***> wrote：

不好意思，因为我这边没有这个特征文件所以不方便测试，我刚更新了代码，如果有什么问题还请告诉我。正常的话train是82783张图片，val是40504张图片

**Comment by AndersonStra** [comment]
不好意思，我这边好像并没有收到附件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AndersonStra/MuKEA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AndersonStra/MuKEA] hallo，How to acquire the file of“cocobu_att”and“cocobu_box” in the prepare_img.py？thank you！ (Issue #2)





 您好，不好意思这么晚打扰您，有个程序运行上的问题可以请教您嘛？在网上试了好几个方案也没有解决。是在V100上运行的时候，总是会出现下面的错误（图片在附件）。cuda版本是10.1,   tersorflow=2.8.0,    cudatoolkit=11.0.221，期待您的回复。谢谢！
 祝好！
 
 
 
 
 | |
 王凤娟
 |
 |
 ***@***.***
 |
 签名由网易邮箱大师定制
 On 4/7/2022 ***@***.***&gt; wrote：
 
 不好意思，因为我这边没有这个特征文件所以不方便测试，我刚更新了代码，如果有什么问题还请告诉我。正常的话train是82783张图片，val是40504张图片
