### ISSUE TITLE
关于可视化问题

### ISSUE THREAD

**Issue by liu23ff** [AndersonStra/MuKEA#25]
您好，非常感谢您的工作。我有一个问题不是很明白，就是在论文的4.5节中，对应图3中的红色检测框怎么得到的呀，代码中没有找到相应部分，感谢您的解答

**Comment by AndersonStra** [comment]
具体的过程是先得到attention权重最大的区域，然后基于BUTD特征的bounding box绘制

**Comment by liu23ff** [comment]
好的，我研究研究，谢谢
