### ISSUE TITLE
Hello, Why is the training time of this project so long?

### ISSUE THREAD

**Issue by zhongfansun** [AndersonStra/MuKEA#4]
Thank you very much for providing this program, it really helped me a lot.

I used four 3090 GPUs to train this project. As can be seen from the picture below, it takes me about one hour to train an epoch. At this rate, I might need eight days to train 200 epochs. Is eight days normal or Is there something wrong with me? 
![捕获](https://user-images.githubusercontent.com/102452634/162917860-68b49d38-7739-48c2-9f93-aa34ad9ad22a.PNG)

**Comment by AndersonStra** [comment]
When pre-training for the OK-VQA task, it takes 40 min to train an epoch for 200,000 training data on 2 V100 GPUs, taking one hour for  600,000 training data makes sense.  However, 200 epoch setting is only necessary for the fine-tuning stage on the OK-VQA dataset, in my experience, 20 epochs could make the model converge during Ok-VQA's pre-training stage， you can perform an early stop based on the validation set（e.g. test-dev set in VQAv2, it may need changes in the code）.

As for the reason for training time, I guess there are several possible reasons：
* I use all of the 10 annotated answers for training, the training sample was actually expanded tenfold
* the IO time or tensor transfer time between GPU and CPU wastes a lot of time, but I haven't been able to figure out which part of the code is consuming too much time, I will make a detailed test in the future.

**Comment by zhongfansun** [comment]
Thank you very much for your guidance! But I still have some confusions.

During OK-VQA's pre-training stage, after about 20 epochs, how much can the performance on the validation set (e.g. test_dev set in VQAv2) achieve? I want to verify whether the program I am running is correct through the performance. The validation set need **_vqa_img_feature_test_dev.pickle_**, does it obtained by modifying tsv2feature.py and inputing the two files:  **_test2015_resnet101_faster_rcnn_genome_36.tsv_** and **_vqa_test_dev.json_**. Similarly, does **_krvqa_img_feature_test.pickle_** obtained by modifying _**tsv2feature.py**_ and inputing the two files: **_test2015_resnet101_faster_rcnn_genome_36.tsv_** and **_krvqa_test.json_**. I am sorry about that there are too many intermediate files in the data/ folder. Some files are used in the code and some are not. I may need more time to learn how these files are obtained and used

**Comment by AndersonStra** [comment]
If you want to produce the results on OK-VQA, the parameter of dataset should be okvqa, not vqav2. Since there are no answer annotation in vqav2 test set，you may need a validation set(test_dev),  but in okvqa，it is unnecessary to validate on test_dev，test_dev is only for vqav2. 

the main experiments in this paper do not include vqav2，and there is no fine-tuning for vqav2，you can see the results in the appendix of the paper.  If you mean results on OK-VQA，you should get about 25-30% accuracy after 20-30 epoch pretrain on testing set，it corresponds results in ablation experiment（line 'w/o okvqa knowledge'）.

for test_dev，it's right. for krvqa，you may need download origin dataset and extract bottomup features to generate tsv file。the links I provide only contains Coco features，krvqa is not totally based on Coco image

**Comment by zhongfansun** [comment]
I am very grateful for your reply. According to your instructions, I just successfully ran the first epoch of training and validation. I will further study your code, wish you all the best.

**Comment by wangfengjuan** [comment]
> Hello, is the result of your pre-training on VQAV2 normal? There's something wrong with my accuracy. It's all 0

**Comment by zhongfansun** [comment]
> > Hello, is the result of your pre-training on VQAV2 normal? There's something wrong with my accuracy. It's all 0

You need to set _--dataset okvqa_ and it will still pre-train on vqav2. _--dataset vqav2_ is just a test.

**Comment by wangfengjuan** [comment]
> I ran on the okvqa data set before. It was about epoch14, and the preparation rate was 26.57%. This accuracy rate is very different from 42.59 in the article.

**Comment by AndersonStra** [comment]
> > I ran on the okvqa data set before. It was about epoch14, and the preparation rate was 26.57%. This accuracy rate is very different from 42.59 in the article.

26.57% seems to be the results based on pre-training, did you conduct fine-tuning on the OK-VQA, https://github.com/AndersonStra/MuKEA#fine-tuning

**Comment by wangfengjuan** [comment]
好的，明白了。感谢您的回复！


| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/25/2022 ***@***.***> wrote：

I ran on the okvqa data set before. It was about epoch14, and the preparation rate was 26.57%. This accuracy rate is very different from 42.59 in the article.

26.57% seems to be the results based on pre-training, did you conduct fine-tuning on the OK-VQA, https://github.com/AndersonStra/MuKEA#fine-tuning

**Comment by wangfengjuan** [comment]
> 



> > > 你好，你的VQAV2预演结果正常吗？
> 
> 您需要设置_--dataset okvqa_，它仍会在vqav2上进行预训练。_--dataset vqav2只是_一个测试。

那是不需要在命令行参数设置--dataset vqa2.0了嘛？但作者说：文章中compare的最终结果是先在vqa2.0预训练，然后在okvqa上微调的结果，如果只使用OKVQA数据，对应的是GitHub中 w/o pre-training 底下这个命令跑出来的结果，正常应该是36左右。

**Comment by wangfengjuan** [comment]
好的，谢谢您的回复，在OKvqa上进行预训练，是不是 不用带上红线部分的krvqa了？


| |
王凤娟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/29/2022 ***@***.***> wrote：

你好，你的VQAV2预演结果正常吗？

您需要设置_--dataset okvqa_，它仍会在vqav2上进行预训练。_--dataset vqav2只是_一个测试。

那是不需要在命令行参数设置--dataset vqa2.0了嘛？但作者说：文章中compare的最终结果是先在vqa2.0预训练，然后在okvqa上微调的结果，如果只使用OKVQA数据，对应的是GitHub中 w/o pre-training 底下这个命令跑出来的结果，正常应该是36左右。

只在OKVQA上训练，运行python train.py --embedding --model_dir model_save_dir --dataset okvqa/krvqa --validate命令，在VQA2.0上预训练后微调，依次运行 python train.py --embedding --model_dir model_save_dir --dataset okvqa --pretrain --accumulate --validate 和python train.py --embedding --model_dir model_save_dir --dataset okvqa --load_pthpath model_save_dir/checkpoint --accumulate --validate

**Comment by wangfengjuan** [comment]
> > > 
> > 
> > 
> > > > > 你好，你的VQAV2预演结果正常吗？
> > > 
> > > 
> > > 您需要设置_--dataset okvqa_，它仍会在vqav2上进行预训练。_--dataset vqav2只是_一个测试。
> > 
> > 
> > 那是预先准备好的测试结果好的结果吗？ ，就是在 GitHub 中没有预训练下这个命令跑出来的结果，正常应该是 36 左右。
> 
> 只在OKVQA上运行train.py --embedmodel_dir model_save_dir --dataset okvqqrvqa --vQA20上预训练后训练验证命令，在python train.py --embedding -- model_dir model_save_dir --dataset okvqa --pretrain --accumulate --validate 和python train.py --embedding --model_dir model_save_dir --dataset okvqa --load_pthpath model_save_dir/checkpoint --accumulate --validate

您好，我在运行命令python train.py --embedding --model_dir model_save_dir --dataset okvqa --load_pthpath model_save_dir/checkpoint --accumulate --validate会出现下面问题，也是无法加载lxmert模型的权重，
OSError: Unable to load weights from pytorch checkpoint file for 'unc-nlp/lxmert-base-uncased' at '/home/stormai/.cache/torch/transformers/5399e7622c3fba3187db0c4e3aa122649331729c6277c0ee08e1b454a6d3fd6d.5f34224e0933c808bf4330e36313dfcad321a7cd2d3b97f6d169b3ad6417eb2e'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
