### ISSUE TITLE
OSError: Can't load weights for './premodel'. 

### ISSUE THREAD

**Issue by PamelaDDD** [AndersonStra/MuKEA#5]
![image](https://user-images.githubusercontent.com/33123364/163403783-e4ed7be7-1ddc-4d92-8083-836a48444043.png)

when pretraining I met this problem. where can I download the pre-trained model?

**Comment by AndersonStra** [comment]
corresponding code line has changed to `model = LxmertModel.from_pretrained('unc-nlp/lxmert-base-uncased', config=config)`, please run `git pull` to get the latest updated code.

**Comment by PamelaDDD** [comment]
Thank you!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 晚上11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AndersonStra/MuKEA] OSError: Can&#39;t load weights for &#39;./premodel&#39;.  (Issue #5)





 
corresponding code line has changed to model = LxmertModel.from_pretrained('unc-nlp/lxmert-base-uncased', config=config), please run git pull to get the latest updated code.
